### ISSUE TITLE
Libpebble :error: unpack requires a string argument of length 78

### ISSUE THREAD

**Issue by klanestro** [Hexxeh/libpebble#22]
I am connected and I got the 7 minute workout and a few watchfaces to upload to my pebble from my ubuntu laptop.
I can't get around this problem.  get_time works but it seems some pbw don't work this is my stacktrace
Thanks

talisman@talisman-Pangolin-Performance:~$ cd projects/libpebble
talisman@talisman-Pangolin-Performance:~/projects/libpebble$ python ./p.py --pebble_id 00:18:33:A7:D2:2D --lightblue load '/home/talisman/Downloads/LCARS2.pbw'  --nolaunch
[DEBUG   ] LightBlue process has started on pid 25111
[DEBUG   ] Connection established to 00:18:33:A7:D2:2D
[DEBUG   ] Initializing reader thread
[DEBUG   ] Reader thread loaded on tid Thread-1
Traceback (most recent call last):
  File "/home/talisman/projects/libpebble/pebble/pebble.py", line 266, in _reader
    resp = self._internal_endpoint_handlers[endpoint](endpoint, resp)
  File "/home/talisman/projects/libpebble/pebble/pebble.py", line 695, in _appbank_status_response
    unpack("!II32s32sIH", data[offset:offset+appinfo_size])
error: unpack requires a string argument of length 78
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/talisman/projects/libpebble/pebble/pebble.py", line 272, in _reader
    raise PebbleError(self.id, "Lost connection to Pebble")
PebbleError: Lost connection to Pebble (ID:00:18:33:A7:D2:2D

what do I need to research for this?

Running Ubuntu

**Comment by klanestro** [comment]
1.12 firmware

**Comment by BlackMac** [comment]
How did you solve it?

**Comment by klanestro** [comment]
I really did not solve it.  But everything works so long as my watch does not get "full"  It has very little memory and it works as expected until I load to much on it(or that last apk).  then even the list command get's this error.  This is the error I get when the watch can't accept any more data.  I don't think it is libpebble's fault I think it is the pebble firmware.  Now i Have 3 additional watchfaces and 2 programs.  After that this is the error

**Comment by BlackMac** [comment]
I believe this could be an overflow in libpebble I will look into it myself tonight.

**Comment by klanestro** [comment]
Well I hope you can fix it.

**Comment by klanestro** [comment]
It's not that my watch is full, This is an error in libpebble, I just got an android and am able to install more, Still had this error, then went back to the app and installed more till it was full
